export const authTypes = {
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  USER_LOAD: "USER_LOAD",
};

export const todoTypes = {
  GET_TODO: "GET_TODO",
};
